config/routes.rb
Rails.application.routes.draw do
  resources :welcome
  resources :rooms
  root 'welcome#index'
  get '/rooms' => 'rooms#index'
  get 'signup' => 'users#new'
  resources :users
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  # post '/rooms/new' => 'rooms#new'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
# ApplicationRecord
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/room.rb
# Room
class Room < ApplicationRecord
  validates :name, uniqueness: { message: 'name used already!' }
  validates :image, presence: { message: 'Please enter image url' }
  validates :capacity, presence: true
  validates :name, presence: true
  validates :location, presence: true
end

app/models/user.rb
# User
class User < ApplicationRecord
  has_secure_password
  def admin?
    role == 'admin'
  end

  validates :password, confirmation: true
  validates :password_confirmation, presence: true
  validates :password, length: { in: 8..20 }
end

app/controllers/application_controller.rb
# ApplicationController
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def require_user
    redirect_to '/login' unless current_user
  end

  def require_admin
    redirect_to '/' unless current_user.admin?
  end
end

app/controllers/rooms_controller.rb
# RoomsController
class RoomsController < ApplicationController
  before_action :find_room, only: %i[show edit update destroy]
  before_action :require_user, only: %i[index show]
  before_action :require_admin, only: %i[edit destroy]
  def index
    @rooms = Room.all.order('created_at DESC').decorate
  end

  def show
    @room = Room.find(params[:id]).decorate
  end

  def new
    @room = Room.new.decorate
  end

  def create
    @room = Room.new(room_params).decorate
    if @room.save
      redirect_to rooms_path, alert: 'You have successfully created a new room'
    else
      render 'new'
    end
  end

  def edit; end

  def update
    if @room.update(room_params)
      redirect_to room_path(@room), alert: 'Room successfully updated'
    else
      render 'edit'
    end
  end

  def destroy
    @room.destroy.decorate
    redirect_to rooms_path, alert: 'You have successfully deleted the room'
  end

  private

  def room_params
    params.require(:room).permit(:name, :location, :capacity)
  end

  def find_room
    
  end
end

app/controllers/sessions_controller.rb
# SessionsController
class SessionsController < ApplicationController
  def new; end

  def create
    @user = User.find_by_email(params[:session][:email])
    if @user && @user.authenticate(params[:session][:password])
      session[:user_id] = @user.id
      redirect_to rooms_path, alert: 'Signed in successfully.'
    else
      redirect_to '/login', alert: 'Invalid email/password combination'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to '/', alert: 'Signed out successfully.'
  end
end

app/controllers/users_controller.rb
# UsersController
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to rooms_path, alert: 'Welcome! You have signed up successfully.'
    else
      redirect_to '/signup'
    end
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password)
  end
end

app/controllers/welcome_controller.rb
# WelcomeController
class WelcomeController < ApplicationController
  def index; end
end

app/helpers/application_helper.rb
# ApplicationHelper
module ApplicationHelper
end

app/helpers/rooms_helper.rb
# RoomsHelper
module RoomsHelper
end

app/helpers/sessions_helper.rb
# SessionsHelper
module SessionsHelper
end

app/helpers/users_helper.rb
# UsersHelper
module UsersHelper
end

app/helpers/welcome_helper.rb
# WelcomeHelper
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RoomCheckingApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Acme" rel="stylesheet">
  </head>

  <body>
  <% if notice %>
  <div id="notice-wrapper">
    <p class="notice"><%= notice %></p>
  </div>
  <% elsif alert %>
  <div class="notice-wrapper">
    <p class="alert"><%= alert %></p>
  </div>
  <% end %>
    <%= yield %>
  </body>
</html>

app/views/partials/_footer.html.erb
<footer class="page-footer">
    <div class="footer-copyright">
      <div class="container">
      © 2017 Copyright <strong>Seun Adekunle</strong>
      <a class="grey-text text-lighten-4 right" href="https://www.github.com/seunadex" target="_blank">GitHub</a>
      </div>
    </div>
  </footer>

app/views/partials/_form.html.erb
<%= simple_form_for @room do |f| %>
  <%= f.input :name, label: 'Room name', placeholder: 'Room', error: 'Room name is mandatory, please specify one' %>
  <%= f.input :location, placeholder: 'specify floor and wing', error: 'Please specify location' %>
  <%= f.input :capacity, error: 'Please specify capacity'%>
  <%= f.input :image, placeholder: 'input image url'%>
  <%= f.button :submit, data: { disable_with: "Loading..." } %>
<% end %>

app/views/partials/_login_form.html.erb
<%= simple_form_for(:session, url: login_path) do |f| %>
  <%= f.input :email,autofocus: true, :placeholder => "your email here", class: "placeholder" %>
  <%= f.input :password, :placeholder => "Password" %> 
  <%= f.submit "Log in", class: "btn", data: { disable_with: "Logging in..." } %>
<% end %>

app/views/partials/_navbar.html.erb
<nav role="navigation">
  <div class="nav-wrapper">
    <div class="container">
      <%= link_to 'RoomChecker', rooms_path, class: 'brand-logo' %>
      <% if current_user %>
        <ul id="nav-mobile" class="right">
          <li class="current-user space"><i class="material-icons left">person</i><%= current_user.first_name.upcase %></li>
          <li class="space"><%= link_to 'Home', root_path %></li>
          <% if current_user && current_user.admin? %>
            <li class="space"><%= link_to 'Add room', new_room_path %></li>
          <% end %>
            <li class="space"><%= link_to "Log out", logout_path, method: "delete" %></li>
        </ul>
      <% else %>
        <ul id="nav-mobile" class="right">
          <li><i class="material-icons left">login</i><%= link_to 'Login', login_path %></li>
          <li><i class="material-icons left">person</i><%= link_to 'Sign up', new_user_path %></li>
        </ul>
      <% end %>
    </div>
  </div>
</nav>

app/views/partials/_new_room_form.html.erb
<%= simple_form_for @room do |f| %>
  <%= f.input :name, label: 'Room name', placeholder: 'Room', error: 'Room name is mandatory, please specify one' %>
  <%= f.input :location, placeholder: 'specify floor and wing', error: 'Please specify location' %>
  <%= f.input :capacity, error: 'Please specify capacity'%>
  <%= f.input :image, placeholder: 'input image url'%>
  <%= f.button :submit, data: { disable_with: "Loading..." } %>
<% end %>

app/views/partials/_new_user_form.html.erb
<%= simple_form_for @user do |f| %>
  <%= f.input :first_name, autofocus: true, error: 'first_name is mandatory, please specify one' %>
  <%= f.input :last_name, error: 'last_name is mandatory, please specify one'%>
  <%= f.input :email %>
  <%= f.input :password %>
  <%= f.input :password_confirmation %>
  <%= f.submit "Sign up", class: 'btn', data: { disable_with: "Signing up..." } %>
<% end %>

app/views/rooms/edit.html.erb
<%= render "partials/navbar" %>
<div class="auth">
  <div class="overlay">
    <div class="container">
      <div class="form">
        <h2>Edit room</h2>
          <%= render "partials/new_room_form" %>
      </div>
    </div>
  </div>
</div>

app/views/rooms/index.html.erb
<%= render "partials/navbar" %>
<h1>Rooms</h1>
    <p>Availability: <%= @rooms.count %></p>

<div class="row">
    <% @rooms.each do |room| %>
        <div class="col s12 m4">
            <div class="row room-list">
                <div class="col s12 m12">
                    <div class="image"><%= image_tag room.image, class: 'image' %></div>
                </div>
                <div class="col s12 m12">
                    <h4><%= room.name %></h4>
                </div>
                <div class="col s6 m6">
                    <p>Location: <%= room.location %></p>
                </div>
                <div class="col s6 m6">
                    <p>Capacity: <%= room.capacity %></p>
                </div>
                <div class="col s6 m6">
                    <p>Availability: <%= room.availability %></p>
                </div>
                <div class="col s6 m6">
                <button class="waves-effect blue waves-light btn"><i class="material-icons right">view_compact</i><%= link_to 'View', room, class: 'view-room' %></button>
                </div>
            </div>
        </div>
    <% end %>
</div>
<%= render "partials/footer" %>

app/views/rooms/new.html.erb
<%= render "partials/navbar" %>
<div class="auth">
  <div class="overlay">
    <div class="container">
      <div class="form">
        <h3>Add a new room</h3>
          <%= render "partials/new_room_form" %>
      </div>
    </div>
  </div>
</div>

app/views/rooms/show.html.erb
<%= render "partials/navbar" %>
<div class="single-room">
  <div class="row">
    <div class="col s12 m7">
      <div><%= image_tag @room.image, class: 'image-tag' %></div>
    </div>
    <div class="col s6 m5">
      <div class="row">
        <div class="desc">
          <div class="col m12">
            <h2><%= @room.name %></h2>
          </div>
          <div class="col m12">
            <p>Description: coming soon</p>
          </div>
          <div class="col m6">
            <p>Location: <%= @room.location %></p>
          </div>
          <div class="col m6">
            <p>Capacity: <%= @room.capacity %></p>
          </div>
          <% if current_user && !current_user.admin? %>
          <div class="col m6">
            <p>Availability: <%= @room.availability %></p>
          </div>
          <% end %>
          <% if current_user.admin? %>
          <div class="col m12">
            <p>Availability: <%= @room.availability %></p>
          </div>
          <% end %>
          <% if current_user && !current_user.admin? %>
            <div class="col m6">
              <button class="waves-effect blue waves-light btn"><i class="material-icons right">cloud</i>Book Room</button>
            </div>
          <% end %>
          <% if current_user && current_user.admin? %>
          <div class="col m6">
            <%= link_to 'Edit', edit_room_path(@room), class: 'waves-effect blue waves-light btn' %>
          </div>
          <div class="col m6">
            <%= link_to 'Delete', room_path(@room), method: :delete, data: { confirm: 'Are you sure you want to delete the room?' }, class: 'waves-effect blue waves-light btn' %>
          </div>
          <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<div class="auth">
  <div class="overlay">
    <div class="log">
      <div class="container">
        <div class="form">
        <%= image_tag "signupIcon.png", class: "login-img" %>
          <%= render 'partials/new_user_form' %>
          <p>Already have an Account? <%= link_to 'Login', login_path %> here.
        </div>
      </div>
    </div>
  </div>
</div>

app/views/welcome/index.html.erb
<%= render "partials/navbar" %>
<div class="index">
    <div class="overlay">
        <div class="welcome">
            <h1>Welcome!, Need a room?</h1>
                <button class="waves-effect blue waves-light btn"><i class="material-icons left">view_comfy</i><%= link_to "View all Rooms", rooms_path, class: 'view-room' %>
                </button>
        </div>
    </div>
</div>